### ISSUE TITLE
Characterize predictive performance of each ML algorithm in our toolbox vs various data sets for a representative set of queries

### ISSUE THREAD

**Issue by ejsegall** [cognoma/machine-learning#12]
Issue #5 describes a table of ML methods. (This is the "toolbox" referred to in the title)
Issue #11 describes creating a set of sample data sets. 
This issue is a task that consists of:
- Running each algorithm on each data set and evaluating its predictive quality. 
- To the best of your capability, provide a few words explaining the results

Since there are a lot of algorithms and a lot of datasets there is an opportunity for many people to participate in this task.

@dhimmel

**Comment by ejsegall** [comment]
sameertipnis@gmail.com is interested in participating

**Comment by RenasonceGent** [comment]
I will work on a plug and play architecture for the algorithms.

**Comment by ejsegall** [comment]
@RenasonceGent: please see issue #13
