### ISSUE TITLE
Facilitate application of multiple methods to multiple data sets

### ISSUE THREAD

**Issue by ejsegall** [cognoma/machine-learning#13]
Issue #13 requires application of multiple methods to multiple data sets.
To simplify this process, it would be helpful to set up a reusable workbook or code set that supports plugging in different methods. 

@renasoncegent has expressed interest in this task

@dhimmel

**Comment by dhimmel** [comment]
@renasoncegent and I will be creating a modular design, inspired by this [example code](http://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html) and will report back with progress.

**Comment by ypar** [comment]
Semi-related... I find hdbscan notebooks to be incredibly informative and stylish. In case some of you haven't seen analysis notebooks before, I link an example here.

[hdbscan benchmarking scalability](https://github.com/lmcinnes/hdbscan/blob/master/notebooks/Benchmarking%20scalability%20of%20clustering%20implementations%202D%20v0.7.ipynb)

**Comment by dhimmel** [comment]
Closing this issue.

See #27 to claim and implement an sklearn algorithm of your choosing.
