### ISSUE TITLE
Should testing data be used for unsupervised feature tranformation or selection

### ISSUE THREAD

**Issue by dhimmel** [cognoma/machine-learning#23]
Imagine splitting the data as follows, where X is the complete feature matrix and y is the outcome array ([`train_test_split` doc](http://scikit-learn.org/stable/modules/generated/sklearn.cross_validation.train_test_split.html)):

``` python
X_train, X_test, y_train, y_test = sklearn.cross_validation.train_test_split(X, y)
```

The goal of this discussion is to evaluate whether we should apply any operations on `X` (the union of `X_train` and `X_test`). @htcai cautioned against feature selection/transformation on the entire `X`: https://github.com/cognoma/machine-learning/pull/18#issuecomment-236251279.

What are the drawbacks and advantages of selection/transformation on an `X` that includes `X_test`?

**Comment by htcai** [comment]
[k-fold cross-validation](https://en.wikipedia.org/wiki/Cross-validation_%28statistics%29#k-fold_cross-validation) might be useful for undermining/eliminating biased estimate of the model's performance. This method is also available in [sklearn](http://scikit-learn.org/stable/modules/cross_validation.html#k-fold). I'm not sure whether this has already been taken into account. Just in case.

**Comment by dhimmel** [comment]
@htcai my pull request #18 uses [`GridSearchCV`](http://scikit-learn.org/stable/modules/generated/sklearn.grid_search.GridSearchCV.html), which performs cross validation behind the scenes. For your reference, the cross validation occurs inside `X_train` as defined in the [comment above](#issue-168681667).
