### ISSUE TITLE
Save performance-related parameters when processing queries (for later response time prediction)

### ISSUE THREAD

**Issue by ejsegall** [cognoma/machine-learning#6]
Some queries will be much faster than others. It will be very helpful to both end users and UI designers to have info about how long a query can be expected to take. 

If we save performance-related parameters such as the query itself, the sizes of referenced tables, and relevant query time intervals (database, post-processing), then we will have lots of data to mine later for predicting response time.

**Comment by awm33** [comment]
The task service will have the overall start and end time. To get finer grain timings, I'd suggest creating a database table to consistently record this information. You guys could access this directly using SQL or the API could expose it.

**Comment by rdvelazquez** [comment]
Although this would be a nice feature I don't think there are plans to include it at this time. Closing this issue.

**Comment by rdvelazquez** [comment]
@dhimmel I'd like to clean-up the issues tab by closing issues that are resolved or are no longer relevant. I think this will allow us to more clearly see what still needs to be addressed. I can try to leave comments in the issues I'm closing to state why it's being closed and provide links to PRs that address the issue (if applicable).

Before I did this I thought I should check with you first... do you think this would be helpful or would you prefer to leave all issues open for now?
