### ISSUE TITLE
Add stronger support for pip

### ISSUE THREAD

**Issue by jessept** [cognoma/machine-learning#61]
cognoma runs into a specific import issue when installing directly from github:

```
>>> from cognoml import analysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Projects/miniconda3/envs/test_cognoma/lib/python3.5/site-packages/cognoml/analysis.py", line 11, in <module>
    from cognoml.classifiers.logistic_regression import grid_search
ImportError: No module named 'cognoml.classifiers'
```

This does not appear when installing in conda, but makes installing with pip more time-consuming. This would require some exploration into the files necessary to be able to pip install directly from github.

**Comment by dhimmel** [comment]
@jessept can you post the pip command you used?

Also I edited your post to put the error message in a code block using triple backticks.

**Comment by jessept** [comment]
@dhimmel Pip command used: 
`pip install git+git://github.com/cognoma/machine-learning`
