### ISSUE TITLE
Should cognoml reside in a separate repo?

### ISSUE THREAD

**Issue by dhimmel** [cognoma/machine-learning#64]
cognoml is the Python package we're developing for machine-learning

I'm starting to think this would simplify things.

@awm33 what do you think?

**Comment by awm33** [comment]
It might. So this repo would be the "playground", while cognoml is "production ready" and can be consumed by applications?

**Comment by dhimmel** [comment]
> So this repo would be the "playground", while cognoml is "production ready" and can be consumed by applications?

Yeah, `machine-learning` will be a data analysis repository (tracks notebooks, figures, datasets). `cognoml` will be a python package repository. This will avoid confusion where it's not clear whether a file is needed for the package or for the exploratory analyses.

**Comment by awm33** [comment]
That makes sense

**Comment by dhimmel** [comment]
Okay, I'll create a `cognoml` repo once #62 is merged.

From [this StackOverflow answer](http://stackoverflow.com/a/6006679/4651668), here's a beastly git command to take only the package-relevant files and rewrite history to include only relevant commits.

``` sh
git filter-branch \
    --prune-empty \
    --index-filter '
        git ls-tree -z -r --name-only --full-tree $GIT_COMMIT \
        | grep --null-data --invert-match "^LICENSE.md$" \
        | grep --null-data --invert-match "^setup.py$" \
        | grep --null-data --invert-match "^cognoml" \
        | xargs --null --no-run-if-empty git rm --cached -r
    ' \
    -- \
    --all
```

This command currently will transfer the `LICENSE.md` and `setup.py` files to the new repo as well as everything in the `cognoml` directory.

**Comment by dhimmel** [comment]
Okay I used the [above command](#issuecomment-255856647) to populate the new cognoml repository up to cognoma/cognoml@d4ab12c1baf166ca6ae7612b0e414c2d41fbea80.
