### ISSUE TITLE
Standardize the plots in notebooks

### ISSUE THREAD

**Issue by patrick-miller** [cognoma/machine-learning#97]
I wanted to open this issue so that we could discuss what framework we wanted to use in the notebook that we export for our users. There are a lot of [options](https://www.youtube.com/watch?v=FytuB8nFHPQ). 

Right now, the majority of the plots are in **matplotlib/seaborn**. There is a pretty good replication of R's ggplot2 with yhat's **[ggpy](https://github.com/yhat/ggpy)**.

We can use JavaScript based, dynamic plots with **bokeh** or **Vega**. There has already been some work done with Vega (#74, #77, #84), and these can be incorporated into notebooks. The benefit of using Vega is that once we build a frontend results viewer, presumably we will be moving towards this dynamic method of displaying plots. Maintaining consistency would be a plus.

One issue with displaying Vega plots with ipyvega, is that (as detailed in this [ipyvega pull request](https://github.com/vega/ipyvega/pull/32)) the plots are exported to a static image when viewed through GitHub or nbviewer. Only live notebooks get the JavaScript version. As we are going to be serving a static notebook, I assume we would have the same result. I'll be looking into if [this new project](https://github.com/altair-viz/jupyter_vega) holds any answers.

**Comment by George-Zipperlen** [comment]
Thanks @patrick-miller for the pointer to https://github.com/altair-viz/jupyter_vega.

I will look into this.

I had reached a brick wall with altair/vega-lite in that some of the graph attributes were not accessible in the available json properties / python classes.

For example horizontal / vertical orientation of axis and legend.  The examples force a horizontal orientation to the heatmap legend (quantitative scale), and a vertical orientation to a scatterplot legend with nominal scale.  If I tried using 'vertical' or 'horizontal' in a legend definition, it just wouldn't work.

**Comment by dhimmel** [comment]
@patrick-miller I think your comment does a good job summarizing the options. I wish I were more familiar with the options. I've never used bokeh or ggpy, but they both seem like promising options.

I do think it would be nice to get away from seaborn/matplotlib. Seaborn is nice, but has very limited and predefined functionality. And tweaking the raw matplotlib is a pain. But obviously we'd need a better alternative. So everyone feel free to play around and provide feedback on which solution you think is best.

**Comment by George-Zipperlen** [comment]
I propose using Bokeh instead of Vega-Lite for Cognoma visualizations:

+ Bokeh supports interactive charts
+ Grammar of Graphics influenced
+ abstract rendering
+ dynamic downsampling
+ server plot hosting
+ Interacts directly with HTML 5 canvas
+ So it will work both in a Jupyter notebook, and in a dashboard
+ Python API
+ It is possible to easily convert Matplotlib, Seaborn, charts to Bokeh
+ With ggplot.py, it is possible to convert ggplot to Bokeh
+ uses a JSON structure to communicate between python graphic objects and the front end, or server
+ It is mature, supported

Downside to Vega-Lite/Altair

+ it is still under development
+ many high level  abstractions are not yet fully implemented
+ e.g. vertical orientation attribute can be applied to axes, but not to legends. 
+ heatmap legend doesn't work like nominal legend

Downside to ggplot.py

+ Doesn't support ggviz interactive charts
+ does not expose the grammar in the chart itself, i.e. you just get an svg image

**Comment by patrick-miller** [comment]
Those sound like good reasons to me. The embedding of Vega plots in static notebooks is a work-in-progress, so if we want to ship this by the end of the summer, we should probably go a different direction. 

I would think that Bokeh is not as good for use in the results viewer (because it is Python). That is unless you can create a template and then just drop in the new data through JSON, without having to regenerate the plot in Python. It might be OK for us to generate the plot in Python and serve it that way, but that is a question for the frontend/backend teams.

**Comment by George-Zipperlen** [comment]
The full fledged bokeh implementation users a server to mediate between python accessing the data, and javascript handling the client interactions in dashboards.  Json is used to communicate.

I believe one can get at this json without using a bokeh server, but I haven't got that far yet. I'm still going through the tutorials on how to run bokeh in a jupyter notebook.

**Comment by dhimmel** [comment]
I came across this [helpful post](http://pythonplot.com/) comparing python plotting options. Turns out there is another ggplot2 python clone called `plotnine`. See https://github.com/has2k1/plotnine/issues/1

**Comment by rdvelazquez** [comment]
@patrick-miller is this issue now wrapped up by #112?

**Comment by patrick-miller** [comment]
Yes this is closed
